version: '3.3'
services:
#  web:
#    build: .
#    container_name: products
#    volumes:
#      - ./composeexample:/code
#    ports:
#      - "8080:8080"
#    links:
#      - postgres
#
#    depends_on:
#      - postgres

  mongo:
    image: 'bitnami/mongodb:latest'
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"

volumes:
  dbdata:
